sudo: false
arch:
    - amd64
    - ppc64le

language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
 # - 'pypy'
  - 'pypy3'

env:
  - DJANGO_VERSION=2.2.x
  - DJANGO_VERSION=2.1.x
  - DJANGO_VERSION=2.0.x
  - DJANGO_VERSION=1.11.x
  - DJANGO_VERSION=1.10.x
  - DJANGO_VERSION=1.9.x
  - DJANGO_VERSION=1.8.x

matrix:
  include:
    - python: '3.8'
      env: DJANGO_VERSION=master
      dist: xenial  # meet SQLite >=3.8.3 requirement
    - python: '3.7'
      env: DJANGO_VERSION=master
      dist: xenial  # meet SQLite >=3.8.3 requirement
    - python: '3.6'
      env: DJANGO_VERSION=master
      dist: xenial  # meet SQLite >=3.8.3 requirement
    - python: '3.8'
      env: DJANGO_VERSION=3.0.x
      dist: xenial  # meet SQLite >=3.8.3 requirement
    - python: '3.7'
      env: DJANGO_VERSION=3.0.x
      dist: xenial  # meet SQLite >=3.8.3 requirement
    - python: '3.6'
      env: DJANGO_VERSION=3.0.x
      dist: xenial  # meet SQLite >=3.8.3 requirement
  exclude:
    - python: '2.7'
      env: DJANGO_VERSION=2.2.x
    - python: '3.4'
      env: DJANGO_VERSION=2.2.x
    - python: 'pypy'
      env: DJANGO_VERSION=2.2.x
    - python: '2.7'
      env: DJANGO_VERSION=2.1.x
    - python: '3.4'
      env: DJANGO_VERSION=2.1.x
    - python: 'pypy'
      env: DJANGO_VERSION=2.1.x
    - python: '2.7'
      env: DJANGO_VERSION=2.0.x
    - python: 'pypy'
      env: DJANGO_VERSION=2.0.x
    - python: '3.7'
      env: DJANGO_VERSION=1.10.x
    - python: '3.6'
      env: DJANGO_VERSION=1.10.x
    - python: '3.7'
      env: DJANGO_VERSION=1.9.x
    - python: '3.6'
      env: DJANGO_VERSION=1.9.x
    - python: '3.7'
      env: DJANGO_VERSION=1.8.x
    - python: '3.6'
      env: DJANGO_VERSION=1.8.x
  # adding code to remove power run on powersystem
    - python: '2.7'
      env: DJANGO_VERSION=1.11.x
      arch: ppc64le  
    - python: '2.7'
      env: DJANGO_VERSION=1.10.x
      arch: ppc64le  
    - python: '2.7'
      env: DJANGO_VERSION=1.9.x
      arch: ppc64le  
    - python: '2.7'
      env: DJANGO_VERSION=1.8.x
      arch: ppc64le  
      

install:
  - pip install tox coveralls
